[tools]
rojo = "rojo-rbx/rojo@7.5.1"
selene = "kampfkarren/selene@0.28.0"
stylua = "JohnnyMorganz/StyLua@2.1.0"
wally = "UpliftGames/wally@0.3.2"
wally-package-types = "JohnnyMorganz/wally-package-types@1.5.1"
lune = "lune-org/lune@0.10.1"
