name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup rokit
        uses: CompeyDev/setup-rokit@v0.1.2

      - name: Code quality
        run: |
          selene src/
          stylua -c src/